package vista;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
// import javax.swing.JDesktopPane;

/**
 *
 * @author Héctor Sifuentes
 */
public class FrmModulo extends javax.swing.JFrame {

   // public static JDesktopPane jDesktopPane_menu; //CREACION DE SUBMENUS
    
    public FrmModulo() {
        initComponents();      
        this.setLocationRelativeTo(null); //Frame centrado
        this.setTitle("MENÚ PRINCIPAL"); //Titulo del frame
        this.setSize(new Dimension(1200,700)); //Ancho 1200pixeles Altura 700pixeles
        this.setExtendedState(this.MAXIMIZED_BOTH); //Extender en toda la pantalla
        
        this.setLayout(null);   //Inicializando 
   /*     jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width; //ancho de submenus
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height; //alto de submenus
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto-110)); 
        this.add(jDesktopPane_menu);  */
    }
    @Override
        public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconoModulo.png"));
        return retValue;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/fondoTienda.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,1600,700,this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_nuevoUsuario = new javax.swing.JMenuItem();
        jMenuItem2_gestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3_nuevoProducto = new javax.swing.JMenuItem();
        jMenuItem4_gestionarProducto = new javax.swing.JMenuItem();
        jMenuItem5_actualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6_nuevoProveedor = new javax.swing.JMenuItem();
        jMenuItem7_gestionarProveedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8_nuevoCliente = new javax.swing.JMenuItem();
        jMenuItem9_gestionarCliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10_nuevaCategoria = new javax.swing.JMenuItem();
        jMenuItem11_gestionarCategoria = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12_nuevaVenta = new javax.swing.JMenuItem();
        jMenuItem13_gestionarVenta = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14_reporteCliente = new javax.swing.JMenuItem();
        jMenuItem15_reporteProveedor = new javax.swing.JMenuItem();
        jMenuItem16_reporteCategoria = new javax.swing.JMenuItem();
        jMenuItem17_reporteProducto = new javax.swing.JMenuItem();
        jMenuItem20_reporteVenta = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem18_verHistorial = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem19_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 700));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconUsuario.png"))); // NOI18N
        jMenu1.setText("Empleado");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(135, 50));

        jMenuItem1_nuevoUsuario.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem1_nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconNuevoUsuario.png"))); // NOI18N
        jMenuItem1_nuevoUsuario.setText("Nuevo Empleado");
        jMenuItem1_nuevoUsuario.setPreferredSize(new java.awt.Dimension(230, 50));
        jMenuItem1_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_nuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_nuevoUsuario);

        jMenuItem2_gestionarUsuario.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem2_gestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconGestionarUsuario.png"))); // NOI18N
        jMenuItem2_gestionarUsuario.setText("Gestionar Empleado");
        jMenuItem2_gestionarUsuario.setPreferredSize(new java.awt.Dimension(230, 50));
        jMenuItem2_gestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_gestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2_gestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconProducto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(145, 50));

        jMenuItem3_nuevoProducto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem3_nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icNewProducto.png"))); // NOI18N
        jMenuItem3_nuevoProducto.setText("Nuevo Producto");
        jMenuItem3_nuevoProducto.setPreferredSize(new java.awt.Dimension(230, 50));
        jMenuItem3_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_nuevoProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3_nuevoProducto);

        jMenuItem4_gestionarProducto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem4_gestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icGestionProducto.png"))); // NOI18N
        jMenuItem4_gestionarProducto.setText("Gestionar Productos");
        jMenuItem4_gestionarProducto.setPreferredSize(new java.awt.Dimension(230, 50));
        jMenuItem4_gestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_gestionarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4_gestionarProducto);

        jMenuItem5_actualizarStock.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem5_actualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icNuevo.png"))); // NOI18N
        jMenuItem5_actualizarStock.setText("Actualizar Stock");
        jMenuItem5_actualizarStock.setPreferredSize(new java.awt.Dimension(230, 50));
        jMenuItem5_actualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_actualizarStockActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5_actualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconProveedor.png"))); // NOI18N
        jMenu3.setText("Proveedor");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem6_nuevoProveedor.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem6_nuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newProveedor.png"))); // NOI18N
        jMenuItem6_nuevoProveedor.setText("Nuevo Proveedor");
        jMenuItem6_nuevoProveedor.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu3.add(jMenuItem6_nuevoProveedor);

        jMenuItem7_gestionarProveedor.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem7_gestionarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestionProveedor.png"))); // NOI18N
        jMenuItem7_gestionarProveedor.setText("Gestionar Proveedores");
        jMenuItem7_gestionarProveedor.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu3.add(jMenuItem7_gestionarProveedor);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCliente.png"))); // NOI18N
        jMenu4.setText("Cliente");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(140, 50));

        jMenuItem8_nuevoCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem8_nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoCliente.png"))); // NOI18N
        jMenuItem8_nuevoCliente.setText("Nuevo Cliente");
        jMenuItem8_nuevoCliente.setPreferredSize(new java.awt.Dimension(205, 50));
        jMenuItem8_nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_nuevoClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8_nuevoCliente);

        jMenuItem9_gestionarCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem9_gestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem9_gestionarCliente.setText("Gestionar Clientes");
        jMenuItem9_gestionarCliente.setPreferredSize(new java.awt.Dimension(205, 50));
        jMenuItem9_gestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_gestionarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9_gestionarCliente);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCategoria.png"))); // NOI18N
        jMenu5.setText("Categoría");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(145, 50));

        jMenuItem10_nuevaCategoria.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem10_nuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icNuevo.png"))); // NOI18N
        jMenuItem10_nuevaCategoria.setText("Nueva Categoría");
        jMenuItem10_nuevaCategoria.setPreferredSize(new java.awt.Dimension(220, 50));
        jMenuItem10_nuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10_nuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10_nuevaCategoria);

        jMenuItem11_gestionarCategoria.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem11_gestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem11_gestionarCategoria.setText("Gestionar Categorías");
        jMenuItem11_gestionarCategoria.setPreferredSize(new java.awt.Dimension(220, 50));
        jMenuItem11_gestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11_gestionarCategoriaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11_gestionarCategoria);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconVenta.png"))); // NOI18N
        jMenu6.setText("Facturar");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(145, 50));

        jMenuItem12_nuevaVenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem12_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem12_nuevaVenta.setText("Nueva Venta");
        jMenuItem12_nuevaVenta.setPreferredSize(new java.awt.Dimension(220, 50));
        jMenuItem12_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12_nuevaVentaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12_nuevaVenta);

        jMenuItem13_gestionarVenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem13_gestionarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem13_gestionarVenta.setText("Gestionar Ventas");
        jMenuItem13_gestionarVenta.setPreferredSize(new java.awt.Dimension(220, 50));
        jMenu6.add(jMenuItem13_gestionarVenta);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconReporte.png"))); // NOI18N
        jMenu7.setText("Reportes");
        jMenu7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(145, 50));

        jMenuItem14_reporteCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem14_reporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenuItem14_reporteCliente.setText("Reportes Clientes");
        jMenuItem14_reporteCliente.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu7.add(jMenuItem14_reporteCliente);

        jMenuItem15_reporteProveedor.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem15_reporteProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenuItem15_reporteProveedor.setText("Reportes Proveedores");
        jMenuItem15_reporteProveedor.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu7.add(jMenuItem15_reporteProveedor);

        jMenuItem16_reporteCategoria.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem16_reporteCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenuItem16_reporteCategoria.setText("Reportes Categorías");
        jMenuItem16_reporteCategoria.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu7.add(jMenuItem16_reporteCategoria);

        jMenuItem17_reporteProducto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem17_reporteProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenuItem17_reporteProducto.setText("Reportes Productos");
        jMenuItem17_reporteProducto.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu7.add(jMenuItem17_reporteProducto);

        jMenuItem20_reporteVenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem20_reporteVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenuItem20_reporteVenta.setText("Reportes Ventas");
        jMenuItem20_reporteVenta.setPreferredSize(new java.awt.Dimension(240, 50));
        jMenu7.add(jMenuItem20_reporteVenta);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconHistorial.png"))); // NOI18N
        jMenu8.setText("Historial");
        jMenu8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu8.setMinimumSize(new java.awt.Dimension(160, 50));
        jMenu8.setPreferredSize(new java.awt.Dimension(140, 50));

        jMenuItem18_verHistorial.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem18_verHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenuItem18_verHistorial.setText("Ver Historial");
        jMenuItem18_verHistorial.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenu8.add(jMenuItem18_verHistorial);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCerrarSesion.png"))); // NOI18N
        jMenu9.setText("Cerrar Sesión");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu9.setMinimumSize(new java.awt.Dimension(160, 50));
        jMenu9.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem19_cerrarSesion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem19_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCerrarSesion.png"))); // NOI18N
        jMenuItem19_cerrarSesion.setText("Cerrar Sesión");
        jMenuItem19_cerrarSesion.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem19_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19_cerrarSesionActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19_cerrarSesion);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2_gestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_gestionarUsuarioActionPerformed
        InterGestionarUsuario interGestionarUsuario = new InterGestionarUsuario();
        jDesktopPane1.add(interGestionarUsuario);
        interGestionarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem2_gestionarUsuarioActionPerformed

    private void jMenuItem10_nuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10_nuevaCategoriaActionPerformed
        InterCategoria intercategoria = new InterCategoria();
        jDesktopPane1.add(intercategoria);
        intercategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem10_nuevaCategoriaActionPerformed

    private void jMenuItem1_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_nuevoUsuarioActionPerformed
        InterUsuario interUsuario = new InterUsuario();
        jDesktopPane1.add(interUsuario);
        interUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1_nuevoUsuarioActionPerformed

    private void jMenuItem11_gestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11_gestionarCategoriaActionPerformed
       InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
       jDesktopPane1.add(interGestionarCategoria);
       interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem11_gestionarCategoriaActionPerformed

    private void jMenuItem3_nuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_nuevoProductoActionPerformed
       InterProducto interProducto = new InterProducto();
       jDesktopPane1.add(interProducto);
       interProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem3_nuevoProductoActionPerformed

    private void jMenuItem4_gestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_gestionarProductoActionPerformed
       InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
       jDesktopPane1.add(interGestionarProducto);
       interGestionarProducto.setVisible(true); 
    }//GEN-LAST:event_jMenuItem4_gestionarProductoActionPerformed

    private void jMenuItem8_nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_nuevoClienteActionPerformed
       InterCliente interCliente = new InterCliente();
       jDesktopPane1.add(interCliente);
       interCliente.setVisible(true); 
    }//GEN-LAST:event_jMenuItem8_nuevoClienteActionPerformed

    private void jMenuItem9_gestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_gestionarClienteActionPerformed
        InterGestionarCliente interGestionarCliente = new InterGestionarCliente();
        jDesktopPane1.add(interGestionarCliente);
        interGestionarCliente.setVisible(true); 
    }//GEN-LAST:event_jMenuItem9_gestionarClienteActionPerformed

    private void jMenuItem5_actualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_actualizarStockActionPerformed
        InterActualizarStock interActualizarStock = new InterActualizarStock();
        jDesktopPane1.add(interActualizarStock);
        interActualizarStock.setVisible(true); 
    }//GEN-LAST:event_jMenuItem5_actualizarStockActionPerformed

    private void jMenuItem19_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19_cerrarSesionActionPerformed
        System.exit(0);        
        
    }//GEN-LAST:event_jMenuItem19_cerrarSesionActionPerformed

    private void jMenuItem12_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12_nuevaVentaActionPerformed
         InterFacturacion interFacturacion = new InterFacturacion();
         jDesktopPane1.add(interFacturacion);
         interFacturacion.setVisible(true);
    }//GEN-LAST:event_jMenuItem12_nuevaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10_nuevaCategoria;
    private javax.swing.JMenuItem jMenuItem11_gestionarCategoria;
    private javax.swing.JMenuItem jMenuItem12_nuevaVenta;
    private javax.swing.JMenuItem jMenuItem13_gestionarVenta;
    private javax.swing.JMenuItem jMenuItem14_reporteCliente;
    private javax.swing.JMenuItem jMenuItem15_reporteProveedor;
    private javax.swing.JMenuItem jMenuItem16_reporteCategoria;
    private javax.swing.JMenuItem jMenuItem17_reporteProducto;
    private javax.swing.JMenuItem jMenuItem18_verHistorial;
    private javax.swing.JMenuItem jMenuItem19_cerrarSesion;
    private javax.swing.JMenuItem jMenuItem1_nuevoUsuario;
    private javax.swing.JMenuItem jMenuItem20_reporteVenta;
    private javax.swing.JMenuItem jMenuItem2_gestionarUsuario;
    private javax.swing.JMenuItem jMenuItem3_nuevoProducto;
    private javax.swing.JMenuItem jMenuItem4_gestionarProducto;
    private javax.swing.JMenuItem jMenuItem5_actualizarStock;
    private javax.swing.JMenuItem jMenuItem6_nuevoProveedor;
    private javax.swing.JMenuItem jMenuItem7_gestionarProveedor;
    private javax.swing.JMenuItem jMenuItem8_nuevoCliente;
    private javax.swing.JMenuItem jMenuItem9_gestionarCliente;
    // End of variables declaration//GEN-END:variables
}
