package vista;

import conexion.Conexion;
import controlador.Ctrl_Categoria;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
/**
 *
 * @author Héctor Sifuentes
 */
public class InterGestionarCategoria extends javax.swing.JInternalFrame {

    private int Id_categoria;
    
    
    public InterGestionarCategoria() {
        initComponents();
        this.setSize(new Dimension(600,400));
        this.setTitle("GESTIONAR CATEGORÍAS.");
        
        
        this.CargarTablaCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Categoria = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_Descripcion = new javax.swing.JTextField();
        jLabel1_walpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRAR CATEGORÍAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Categoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable_Categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Categoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Actualizar.setBackground(new java.awt.Color(0, 204, 102));
        jButton_Actualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_Actualizar.setText("ACTUALIZAR");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jButton_Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Eliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_Eliminar.setText("ELIMINAR");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 140, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Descripción:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_Descripcion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jPanel3.add(txt_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, 80));

        jLabel1_walpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCategoria.png"))); // NOI18N
        getContentPane().add(jLabel1_walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        if(!txt_Descripcion.getText().isEmpty()){
            Categoria categoria = new Categoria();
            Ctrl_Categoria controlCategoria = new Ctrl_Categoria();
            
            categoria.setDescripcion(txt_Descripcion.getText().trim());
            if(controlCategoria.actualizar(categoria, Id_categoria)){
               JOptionPane.showMessageDialog(null, "CATEGORIA ACTUALIZADA"); 
               txt_Descripcion.setText("");
               this.CargarTablaCategorias();
            }else{
               JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR CATEGORIA");              
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA CATEGORIA");
        }
        
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        if(!txt_Descripcion.getText().isEmpty()){
            Categoria categoria = new Categoria();
            Ctrl_Categoria controlCategoria = new Ctrl_Categoria();
            
            categoria.setDescripcion(txt_Descripcion.getText().trim());
            if(!controlCategoria.eliminar(Id_categoria)){
               JOptionPane.showMessageDialog(null, "CATEGORIA ELIMINADA"); 
               txt_Descripcion.setText("");
               this.CargarTablaCategorias();
            }else{
               JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR CATEGORIA");          
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA CATEGORIA");
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_walpaper;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_Categoria;
    private javax.swing.JTextField txt_Descripcion;
    // End of variables declaration//GEN-END:variables

    
    /*
    
    ** Método para mostrar todas las categorías registradas **
    */
    private void CargarTablaCategorias(){
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select Id_Categoria, descripcion, estado from tb_Categoria";
        Statement st;
        
        try{
            
           st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           InterGestionarCategoria.jTable_Categoria = new JTable(model);
           InterGestionarCategoria.jScrollPane1.setViewportView(InterGestionarCategoria.jTable_Categoria);
           
           model.addColumn("ID_Categoria");
           model.addColumn("Descripción");
           model.addColumn("Estado");
           
           while(rs.next()){
               Object fila[] = new Object[3];
               
               for (int i = 0; i < 3; i++) {
                   fila[i] = rs.getObject(i+1);
               }
               
               model.addRow(fila); 
           }
             con.close();
           
        }
        catch(SQLException e){
            System.out.println("Error en el llenado de la tabla Categoría: " +e);
        }
        
       jTable_Categoria.addMouseListener(new MouseAdapter() {
          @Override
           public void mouseClicked(MouseEvent e){
              int fila_point = jTable_Categoria.rowAtPoint(e.getPoint());
              int columna_point = 0;
              
              if(fila_point > -1){
                   Id_categoria = (int) model.getValueAt(fila_point, columna_point);
                   EnviarDatosCategoriaSeleccionada(Id_categoria);
              }
           }
           
       });
    }
     
     private void EnviarDatosCategoriaSeleccionada(int Id_categoria){
         try {
         Connection con = Conexion.conectar();
         PreparedStatement pst = con.prepareStatement(
                  "select * from tb_Categoria where Id_Categoria = '" + Id_categoria + "'");
         ResultSet rs = pst.executeQuery();
         
         if(rs.next()){
             txt_Descripcion.setText(rs.getString("descripcion"));
           }
         con.close();
         
         }
         catch(SQLException e){
             System.out.println("Error al seleccionar categoría: "+e);
         }
     }
}
