package vista;

import java.awt.Dimension;
import conexion.Conexion;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Héctor Sifuentes
 */
public class InterFacturacion extends javax.swing.JInternalFrame {

    public InterFacturacion() {
        initComponents();
        this.setSize(new Dimension(800, 620));
        this.setTitle("FACTURACIÓN");

        //cargar clientes en la vista Facturacion
        this.CargarComboClientes();
        //cargar productos en la vista Facturacion
        this.CargarComboProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Cliente = new javax.swing.JComboBox<>();
        jComboBox_Producto = new javax.swing.JComboBox<>();
        txt_ClienteBuscar = new javax.swing.JTextField();
        txt_Cantidad = new javax.swing.JTextField();
        jButton_BuscarCliente = new javax.swing.JButton();
        jButton_AñadirProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Subtotal = new javax.swing.JTextField();
        txt_Descuento = new javax.swing.JTextField();
        txt_IVA = new javax.swing.JTextField();
        txt_TOTALPAGAR = new javax.swing.JTextField();
        txt_Efectivo = new javax.swing.JTextField();
        txt_Cambio = new javax.swing.JTextField();
        jButton_CalcularCambio = new javax.swing.JButton();
        jButton_REGISTRARVENTA = new javax.swing.JButton();
        jLabel_walpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FACTURACIÓN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cliente:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Producto:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 90, -1));

        jComboBox_Cliente.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jComboBox_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE CLIENTE:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, -1));

        jComboBox_Producto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jComboBox_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE PRODUCTO:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        txt_ClienteBuscar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        txt_ClienteBuscar.setText("Ingrese DNI Cliente");
        txt_ClienteBuscar.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(txt_ClienteBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 150, -1));

        txt_Cantidad.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        getContentPane().add(txt_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 70, -1));

        jButton_BuscarCliente.setBackground(new java.awt.Color(153, 204, 255));
        jButton_BuscarCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton_BuscarCliente.setText("Buscar");
        jButton_BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_BuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 90, -1));

        jButton_AñadirProducto.setBackground(new java.awt.Color(153, 204, 255));
        jButton_AñadirProducto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton_AñadirProducto.setText("Añadir productos");
        jButton_AñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 170, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 760, 210));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel5.setText("SUBTOTAL:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel6.setText("DESCUENTO:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel7.setText("IVA:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL A PAGAR:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel9.setText("EFECTIVO:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel10.setText("CAMBIO:");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txt_Subtotal.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        txt_Subtotal.setEnabled(false);
        jPanel2.add(txt_Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, -1));

        txt_Descuento.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        txt_Descuento.setEnabled(false);
        jPanel2.add(txt_Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, -1));

        txt_IVA.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        txt_IVA.setEnabled(false);
        jPanel2.add(txt_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, -1));

        txt_TOTALPAGAR.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        txt_TOTALPAGAR.setEnabled(false);
        jPanel2.add(txt_TOTALPAGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));

        txt_Efectivo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jPanel2.add(txt_Efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, -1));

        txt_Cambio.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        txt_Cambio.setEnabled(false);
        jPanel2.add(txt_Cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, -1));

        jButton_CalcularCambio.setBackground(new java.awt.Color(204, 102, 255));
        jButton_CalcularCambio.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton_CalcularCambio.setText("Calcular Cambio");
        jButton_CalcularCambio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_CalcularCambio.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton_CalcularCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalcularCambioActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_CalcularCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 380, 210));

        jButton_REGISTRARVENTA.setBackground(new java.awt.Color(51, 255, 51));
        jButton_REGISTRARVENTA.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton_REGISTRARVENTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FacturaImpresora.png"))); // NOI18N
        jButton_REGISTRARVENTA.setText("Registrar Venta");
        jButton_REGISTRARVENTA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_REGISTRARVENTA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton_REGISTRARVENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 170, 100));

        jLabel_walpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCategoria.png"))); // NOI18N
        getContentPane().add(jLabel_walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AñadirProductoActionPerformed

    private void jButton_CalcularCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalcularCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CalcularCambioActionPerformed

    private void jButton_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarClienteActionPerformed

        String clienteBuscar = txt_ClienteBuscar.getText().trim();
        Connection cn = Conexion.conectar();
        String sql = "select nombre, apellido from tb_Cliente where cedula = '" + clienteBuscar + "'";
        Statement st;
        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                jComboBox_Cliente.setSelectedItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            } else {
                jComboBox_Cliente.setSelectedItem("SELECCIONE CLIENTE:");
                JOptionPane.showMessageDialog(null, "¡DNI DE CLIENTE NO ENCONTRADA!");
            }
            txt_ClienteBuscar.setText("");
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al buscar cliente: " + e);
        }

    }//GEN-LAST:event_jButton_BuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AñadirProducto;
    private javax.swing.JButton jButton_BuscarCliente;
    private javax.swing.JButton jButton_CalcularCambio;
    private javax.swing.JButton jButton_REGISTRARVENTA;
    private javax.swing.JComboBox<String> jComboBox_Cliente;
    private javax.swing.JComboBox<String> jComboBox_Producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_walpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_Productos;
    private javax.swing.JTextField txt_Cambio;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_ClienteBuscar;
    private javax.swing.JTextField txt_Descuento;
    private javax.swing.JTextField txt_Efectivo;
    private javax.swing.JTextField txt_IVA;
    private javax.swing.JTextField txt_Subtotal;
    private javax.swing.JTextField txt_TOTALPAGAR;
    // End of variables declaration//GEN-END:variables

    //metodo para cargar clientes en el jcombobox
    private void CargarComboClientes() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_Cliente";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_Cliente.removeAllItems(); //QUITA LOS ITEMS 1,2,3...
            jComboBox_Cliente.addItem("SELECCIONE CLIENTE:"); //AGREGA EL ITEM POR DEFECTO
            while (rs.next()) {
                jComboBox_Cliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar clientes: " + e);
        }
    }

    //metodo para cargar productos en el jcombobox
    private void CargarComboProductos() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_Producto";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_Producto.removeAllItems(); //QUITA LOS ITEMS 1,2,3...
            jComboBox_Producto.addItem("SELECCIONE PRODUCTO:"); //AGREGA EL ITEM POR DEFECTO
            while (rs.next()) {
                jComboBox_Producto.addItem(rs.getString("nombre"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar productos: " + e);
        }
    }

}
